# Generated by Django 6.0.1 on 2026-01-07 13:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_course_cover_chapter"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                related_name="enrolled_courses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Студенты",
            ),
        ),
    ]
