"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from dotenv import load_dotenv

load_dotenv()

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-4p%7=c431ivpd0*yy4be3h^i5jm*+m(r&+u1p-h5fr#bjuy()-"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    "lms-app-production-ceea.up.railway.app",
    "127.0.0.1",
    "localhost",
]
if "ALLOWED_HOSTS" in os.environ:
    ALLOWED_HOSTS.extend(os.environ["ALLOWED_HOSTS"].split(","))

CSRF_TRUSTED_ORIGINS = [
    "https://lms-app-production-ceea.up.railway.app",
]
if "CSRF_TRUSTED_ORIGINS" in os.environ:
    CSRF_TRUSTED_ORIGINS.extend(os.environ["CSRF_TRUSTED_ORIGINS"].split(","))


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "cloudinary",  # Put cloudinary before apps interacting with it if specific overwrites needed, but for storage usually safe.
    "cloudinary_storage",  # Usually storage comes last to override staticfiles if needed, but docs say before staticfiles.
    # However, standard ImageField + cloudinary_storage needs it installed.
    # While CloudinaryField needs 'cloudinary'.
    "users",
    "courses",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "ru-ru"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type

# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "users.User"

import os
import io

LOGIN_REDIRECT_URL = "course_list"
LOGOUT_REDIRECT_URL = "course_list"

# Parse Cloudinary URL
try:
    import cloudinary
except ImportError:
    pass

CLOUDINARY_URL = os.environ.get("CLOUDINARY_URL")

if CLOUDINARY_URL:
    # Format: cloudinary://<api_key>:<api_secret>@<cloud_name>
    # We can trust cloudinary library to handle the env var if we set it,
    # but for django-cloudinary-storage we need the dict.

    # Removing 'cloudinary://'
    auth_part, cloud_name = CLOUDINARY_URL.replace("cloudinary://", "").split("@")
    api_key, api_secret = auth_part.split(":")

    CLOUDINARY_STORAGE = {
        "CLOUD_NAME": cloud_name,
        "API_KEY": api_key,
        "API_SECRET": api_secret,
    }

    # Configure cloudinary SDK directly
    cloudinary.config(cloud_name=cloud_name, api_key=api_key, api_secret=api_secret)

else:
    CLOUDINARY_STORAGE = {
        "CLOUD_NAME": "your_cloud_name",
        "API_KEY": "your_api_key",
        "API_SECRET": "your_api_secret",
    }

DEFAULT_FILE_STORAGE = "cloudinary_storage.storage.MediaCloudinaryStorage"


MEDIA_URL = "/media/"

